routes/web.php
<?php
use App\Http\Controllers\BrandController;
use App\Http\Controllers\LaptopController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('laptop', 'App\Http\Controllers\LaptopController');
Route::resource('brand', 'App\Http\Controllers\BrandController');

app/Models/Brand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    use HasFactory;

    protected $table = 'brand';

    protected $fillable = ['name'];
    protected $primaryKey = 'id';

    public function laptops()
    {
        return $this->hasMany(Laptop::class);
    }

}

app/Models/Laptop.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Laptop extends Model
{
  protected $table = 'laptop';
  protected $fillable = ['name','brand_id','price','description','image'];
  
  public function brand()
  {
      return $this->belongsTo(Brand::class, 'brand_id', 'id');
  }

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BrandController.php
<?php

namespace App\Http\Controllers;

use App\Models\Brand;
use Illuminate\Http\Request;

class BrandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $brands = Brand::paginate(5);
        return view('brand.index', compact('brands'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('brand.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Brand::create($request->all());

        return redirect()->route('brand.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function show(Brand $brand)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        $brand = Brand::findOrFail($id);
        return view('brand.edit', compact('brand'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $brand = Brand::findOrFail($id);
        $brand->update($request->all());
        return redirect()->route('brand.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Brand::destroy($id);
        return redirect()->route('brand.index');

    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/LaptopController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateLaptopRequest;
use App\Http\Requests\UpdateLaptopRequest;
use App\Models\Brand;
use App\Models\Laptop;
use Illuminate\Http\Request;


class LaptopController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $laptops = Laptop::with('brand');
        $laptops = Laptop::where([
            ['name', '!=', Null],
            [function ($query) use ($request) {
                if (($term = $request->term)) {
                    $query->orWhere('name', 'LIKE', '%' . $term . '%')->get();
                }
            }]
        ])
            ->paginate(5);

        return view('laptop.index', compact('laptops'));

    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $brand = Brand::get();
        return view('laptop.create', compact('brand'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateLaptopRequest $request)
    {
       

        $imageName = time() . '-' . $request->name . '.' . $request->image->extension();

        $request->image->move(public_path('images'),$imageName);
        
        $laptop = Laptop::create([
            'name' => $request->input('name'),
            'brand_id' => $request->input('brand_id'),
            'price' => $request->input('price'),
            'description' => $request->input('description'),
            'image' => $imageName
        ]);
                
        return redirect()->route('laptop.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Laptop  $laptop
     * @return \Illuminate\Http\Response
     */
    public function show(Laptop $laptop)
    {
        return view('laptop.show',compact('laptop'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Laptop  $laptop
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $laptop = Laptop::findOrFail($id);
        $brand = Brand::get();
        return view('laptop.edit', compact('laptop', 'brand'));
    }



    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Laptop  $laptop
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateLaptopRequest $request, $id)
    {
       
        $laptop=Laptop::findOrFail($id);
        $laptop->name = $request->input('name');
        $laptop->brand_id = $request->input('brand_id');
        $laptop->price = $request->input('price');
        $laptop->description = $request->input('description');
        
        if($request->hasFile('image')) {
            $file = $request->file('image');
            $extension = $file->getClientOriginalExtension();
            $filename = time() . '-' . $request->name . '.' . $extension;
            $file->move(public_path('images'), $filename);
            $laptop->image = $filename;
        }
        $laptop->save();
        return redirect()->route('laptop.index');
    
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Laptop  $laptop
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Laptop::destroy($id);
        return redirect()->route('laptop.index');

    }
    
}

resources/views/brand/create.blade.php
@extends('layout')

@section('content')

<br>

    <div class="container">
        <h1>Add Brand</h1>
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
      
        <br>
        <form action="{{ route('brand.store') }}" method="POST" 
        style="background-color: rgba(20, 20, 20, 0.4);
        width: 40%;
        margin: 10px auto;
        padding: 20px; 
        border: 1px solid white; 
        border-radius: 20px;">
            @csrf
            <h3><span>Name</span></h3>
            <input type="text" class="form-control" name="name" placeholder="Enter brand's name">
            <br>
            <button type="submit" class="btn">Submit</button>
        </form>
        <div class="container-fluid px-0">
        <a href="#" onclick="history.back();"><button type="button" name="back" class="btn">Back</button></a>
        </div>
    </div>
@endsection

resources/views/brand/edit.blade.php
@extends('layout')

@section('content')
<div class="container">
        <h1>Edit</h1>
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="container-fluid px-0">
        <a href="#" onclick="history.back();"><button type="button" name="back" class="btn">Back</button></a>
        </div>
        <form action="{{ route('brand.update', $brand->id) }}" method="POST" 
        style="background-color: rgba(20, 20, 20, 0.4);
        width: 40%;
        margin: 10px auto;
        padding: 20px; 
        border: 1px solid white; 
        border-radius: 20px;">
            @csrf
            @method('PUT')
            <span>Name</span>
            <input type="text" class="form-control" value="{{ $brand->name }}" name="name" placeholder="Enter brand's name">
            <button type="submit" class="btn">Submit</button>
        </form>
    </div>
@endsection

resources/views/brand/index.blade.php
@extends('layout')

@section('content')
<br>
    <div class="container">
        <div class="container"><h1>Brands</h1></div>
        <a class="btn" href="{{ route('brand.create') }}">Add New Brand</a>
        <br>
        <div class="container">
                    @foreach($brands as $brand)
            <div class="detail">
                    <h1>Brand: {{ $brand->name }}</h1>
                    
                @foreach($brand->laptops as $laptop)
                 <h3><a href="{{ route('laptop.show',$laptop->id) }}" style="color: white">{{ $laptop->name }}</a></h3>
                @endforeach
                
                    <td>
                        <form action="{{ route('brand.destroy', $brand->id) }}" method="POST">    
                            <a class="btn" href="{{ route('brand.edit', $brand->id) }}">Edit</a>
                            @csrf
                            @method('DELETE')
                            <button class="btn" onclick="return confirm('Are you sure you want to Delete this?')">Delete</button>
                        </form>
                    </td>
                    </div>
            @endforeach
        </table>
        <a href="#" onclick="history.back();"><button type="button" name="back" class="btn">Back</button></a>
        
        </div>

        {{ $brands->links('pagination::bootstrap-4') }}
    </div>
@endsection

resources/views/laptop/create.blade.php
@extends('layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h1 style="font-size: 300%">Add New Product</h1>
            </div>
        </div>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
        <strong>Whoops!</strong> There are problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
        </div>
    @endif
    <form action="{{ route('laptop.store') }}" method="POST" enctype="multipart/form-data" 
    style="background-color: rgba(20, 20, 20, 0.4);
    width: 40%;
    margin: 10px auto;
    padding: 20px; 
    border: 1px solid white; 
    border-radius: 20px;">
    @csrf
    <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name</strong>
                    <input type="text" name="name" class="form-control" placeholder="Enter laptop's name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Brand</strong>
                    <select name="brand_id" class="form-control">
                @foreach($brand as $brand)
                    <option value="{{ $brand->id }}">{{ $brand->name }}</option>
                @endforeach
                </select>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Price</strong>
                    <input type="text" name="price" class="form-control" placeholder="Enter laptop's price">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <strong>Description</strong>
                <input type="text" name="description" class="form-control" placeholder="More about this laptop">
            </div>         
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <strong>Image</strong>
                <input type="file" name="image" class="form-control">
            </div>         
            </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn">Submit</button>
            <a class="btn" href="{{ route('laptop.index') }}"> Back</a>
        </div>
    </div>
    </form>
@endsection

resources/views/laptop/edit.blade.php
@extends('layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h1 style="font-size: 300%">Edit</h1>
            </div>
        </div>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong> There are problems with your input.</strong><br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('laptop.update',$laptop->id) }}" method="POST" enctype="multipart/form-data"
    style="background-color: rgba(20, 20, 20, 0.4);
    width: 40%;
    margin: 10px auto;
    padding: 20px; 
    border: 1px solid white; 
    border-radius: 20px;">
    @csrf
    @method('PUT')
    <input name="id" type="hidden" value="{{ $laptop->id }}">
    <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name</strong>
                    <input type="text" name="name" class="form-control" value="{{ $laptop->name }}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Brand</strong>
                    <select name="brand_id" class="form-control">
                @foreach($brand as $brand)
                    <option value="{{ $brand->id }}"
                        {{ $brand->id == $laptop->brand_id ? 'selected' : '' }}>
                        {{ $brand->name }}
                    </option>
                @endforeach
            </select>

                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <strong>Price</strong>
                <input type="text" name="price" class="form-control" value="{{ $laptop->price }}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <strong>Description</strong>
                <input type="text" name="description" class="form-control" value="{{ $laptop->description }}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                <strong>Image</strong>
                <input type="file" name="image" class="form-control">
            </div>         
            </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">         
            <button type="submit" class="btn">Confirm</button>
            <a href="#" onclick="history.back();"><button type="button" name="back" class="btn">Back</button></a>
        </div>      
    </div>
    </form>
 
@endsection

resources/views/laptop/index.blade.php
@extends('layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left text-center">
                <h3 style="font-size: 300%">Laptops</h3>
            </div>    
        </div>
    </div>
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <span>{{ $message }}</span>
    </div>
    @endif
    <table class="table">
        <tr>
            <th>Image</th>
            <th>Name</th>
            <th>Brand</th>
            <th>Price</th>
            <th>Description</th>
            <th>Action</th>
        </tr>
        @foreach ($laptops as $laptop)
        <tr>
            <td><img width="100" height="100" src="{{ asset('images/' . $laptop->image) }}"></td>
            <td>{{ $laptop->name }}</td>
            <td>{{ $laptop->brand->name }}</td>
            <td>{{ $laptop->price }}</td>
            <td>{{ $laptop->description }}</td>
            <td><form action="{{ route('laptop.destroy',$laptop->id) }}" method="POST" style="border: none">           
            <a class="btn" href="{{ route('laptop.show',$laptop->id) }}">&#128466;</a>
            <a class="btn" href="{{ route('laptop.edit',$laptop->id) }}">&#128396;</a>
            @csrf
            @method('DELETE')
            <button type="submit" onclick="return confirm('Are you sure you want to Delete this?')" class="btn">&#128465;</button>
            </form>
            </td>
        </tr>
        @endforeach
    </table>
    <div class="row justify-content-center">
{{ $laptops->links('pagination::bootstrap-4') }}
</div>
@endsection

resources/views/laptop/show.blade.php
@extends('layout')
@section('content')
<br>
    <div class="row text-center">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h1 style="font-size: 300%">{{ $laptop->name }} Detail</h1>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
    <div class="col-sm-4">       
        <img width="400" height="400" src="{{ asset('images/' . $laptop->image) }}">
        </div>
    <div class="col-sm-8">
    <div class="container">
    <div class="detail">
    
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <h2>Name: {{ $laptop->name }}</h2>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <h4>Brand: {{  $laptop->brand->name }}</h4>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <h4>Price: {{ $laptop->price }}</h4>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <h4>Description: {{ $laptop->description }}</h4>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
         
        <td><form action="{{ route('laptop.destroy',$laptop->id) }}" method="POST" style="border: none">                     
            <a class="btn" href="{{ route('laptop.edit',$laptop->id) }}">&#128396;</a>
            @csrf
            @method('DELETE')
            <button type="submit" onclick="return confirm('Are you sure you want to Delete this?')" class="btn">&#128465;</button>
            </td>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
        <a href="#" onclick="history.back();"><button type="button" name="back" class="btn">Back</button></a>
    </div>
    </div>
    </div>
   
    </div>
    </div>
    
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html>
    <head>

<!-- tạo nav bar -->
<nav class="navbar navbar-expand-lg navbar-black bg-black">
<h1> <img src="/images/logo_3.png" ></h1>

  <a class="navbar-brand" style="font-size: 40px; color: white" href="{{ route('laptop.index') }}">SAC Mart</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link disabled" style="font-size: 20px">Sáng Bright Like A Diamond</a>
      </li>
    </ul>
    <form action="{{ route('laptop.index') }}" method="GET" role="search" class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" name="term" placeholder="Search" aria-label="Search" id="term">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
        <title>SAC Mart</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">  
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet"/>
<!-- </head> -->


        <!-- Tạo side bar -->

<!-- <body> -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: "Lato", sans-serif;
}

.sidebar {
  height: 100%;
  width: 200px;
  position: fixed;
  z-index: 1;
  top: 50;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  transition: 0.5s;
  
}

.sidebar a, .dropdown-btn {
  padding: 6px 8px 6px 16px;
  text-decoration: none;
  font-size: 23px;
  color: #818181;
  display: block;
  transition: 0.3s;
  border: none;
  background: none;
  width: 100%;
  text-align: left;
  cursor: pointer;
  outline: none;
}

.sidebar a:hover, .dropdown-btn:hover {
  color: #f1f1f1;
}

.left {
  width: 70%;
  background: green;
  padding-right:5px;
  box-sizing: border-box;
}

.right {
  width: 30%;
  position: absolute;
  top: 0px;
  right: 0;
  background: yellow;
  height:100%;
}

.sidebar .closebtn {
  position: right;
  top: 0;
  right: 0px;
  font-size: 36px;
  margin-left: 170px;
}

.openbtn {
  font-size: 20px;
  cursor: pointer;
  background-color: #111;
  color: white;
  padding: 10px 15px;
  border: none;
  
}

.openbtn:hover {
  background-color: #444;
}

/* Add an active class to the active dropdown button */
.active {
  
  color: white;
}
/* Dropdown container (hidden by default). Optional: add a lighter background color and some left padding to change the design of the dropdown content */
.dropdown-container {
  display: none;
  background-color: #262626;
  padding-left: 8px;
}
/* Optional: Style the caret down icon */
.fa-caret-down {
  float: right;
  padding-right: 8px;
}
/* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
@media screen and (max-height: 450px) {
  .sidebar {padding-top: 15px;}
  .sidebar a {font-size: 18px;}
}
</style>
</head>




<div>
  <div id="main" style="position: absolute; left:1.7px">
    <button class="openbtn" onmouseover="openNav()">☰</button>  
  </div>
  <div id="mySidebar" class="sidebar" style="position: absolute">
  
  <a href="javascript:void(0)" class="closebtn" onmouseover="closeNav()">×</a>
  <a href="{{ route('laptop.index') }}">Home</a>
  <button class="dropdown-btn">Brands
    <i class="fa fa-caret-down"></i>
  </button>
  <div class="dropdown-container">
    <a href="{{ route('brand.index') }}">All Brands</a>
    <a href="{{ route('brand.create') }}">Add New Brands</a>
  </div>
  <button class="dropdown-btn">Laptops
    <i class="fa fa-caret-down"></i>
  </button>
  <div class="dropdown-container">
    <a href="{{ route('laptop.index') }}">All Laptops</a>
    <a href="{{ route('laptop.create') }}">Add Laptop</a>
  </div>
  </div>
</div>

<script>
function openNav() {
  document.getElementById("mySidebar").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
  document.getElementById("mySidebar").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
/* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
var dropdown = document.getElementsByClassName("dropdown-btn");
var i;

for (i = 0; i < dropdown.length; i++) {
  dropdown[i].addEventListener("click", function() {
  this.classList.toggle("active");
  var dropdownContent = this.nextElementSibling;
  if (dropdownContent.style.display === "block") {
  dropdownContent.style.display = "none";
  } else {
  dropdownContent.style.display = "block";
  }
  });
}
</script>
   



    <!-- liên -->
<body>
<style>
head {
    color: white;
    text-align: center;
}
body {
    font-family: Georgia;
    font-size: 18px;
    color:  white;
    text-align: center;
    background-size: 100% 100%;
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-image: url('https://wallup.net/wp-content/uploads/2017/11/23/526001-computer-keyboards.jpg');
}
table{
    background-color: rgba(20, 20, 20, 0.3);
    margin: 50px 10px 50px 10px;
    text-align: left;
    color: white;
    border: 1px solid white;    
}
tr {
    background-color: rgba(20, 20, 20, 0.2);
    margin: 20px auto;
    text-align: left;
    color: white;
    border: 1px solid white;   
}
th, td{
    border: none;
    height: 30px;
    padding: 2px;
}

.input-group {
    margin: 10px 0px 5px 0px;
}
.input-group label {
    display: block;
    text-align: left;
    margin: 2px;
    color:  white;
}
.input-group input {
    height: 30px;
    width: 100%;
    padding: 5px 10px;
    font-size: 16px;
    border-radius: 5px;
    border: none;
}
.btn {
    margin: 5px auto;
    padding: 10px 15px;
    font-size: 20px;
    color: white;
    background-color: rgba(20, 20, 20, 0.4);
    border: 1px solid white;
    border-radius: 5px;
}

.detail {
    margin: 10px 30px;
    padding: 20px; 
    border: 1px solid white; 
    border-radius: 20px; 
    background-color: rgba(20, 20, 20, 0.4);
}
</style>
<div class="container">
    @yield('content')
</div>
</body>
</html>